name: Android
on:
  push:
    branches:
    - android

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3       
    - uses: actions/setup-java@v1
      with:
        java-version: '17'
    - uses: subosito/flutter-action@v2
      with:
          channel: 'stable'

    - name: 'Create env file'
      run: |
          touch .env
          echo HOST: ${{secrets.HOST}} >> .env
          cat .env
    
   # Get flutter dependencies.
    - run: flutter pub get
    
    # Build apk.
    - run: flutter build apk --multidex
    
    # Upload generated apk to the artifacts.
    - uses: actions/upload-artifact@master
      with:
        name: apk-release
        path: build/app/outputs/flutter-apk/app-release.apk

    - name: Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1.3.4
      with:
        appId: ${{secrets.FIREBASE_APP_ID}}
        token: ${{secrets.FIREBASE_TOKEN}}
        groups: android_users
        file: build/app/outputs/flutter-apk/app-release.apk